networks:
  default:
    name: xoxxox_netmid
    external: true
services:
  xoxxox_sttoaw:
    image: xoxxox/envoai:001
    container_name: xoxxox_sttoaw
    volumes:
    - ../../../export:/opt/common
    env_file:
    - ./envdir.txt
    - ${HOME}/sec/key/.envath_oai.txt
    ports:
    - 12101:80
    command: "python /opt/common/bin/xoxxox/srvstt.py --engine xoxxox/engine_sttoaw"
